import type { Step } from '../types/index.ts'
import type { AlgorithmId } from './algorithms.ts'

export interface PseudocodeLine {
  code: string
  stepTypes: Step['type'][]
}

export type Pseudocode = PseudocodeLine[]

export const PSEUDOCODE: Record<AlgorithmId, Pseudocode> = {
  'bubble-sort': [
    { code: 'for i = 0 to n-2', stepTypes: [] },
    { code: '  for j = 0 to n-i-2', stepTypes: [] },
    { code: '    compare a[j] and a[j+1]', stepTypes: ['compare'] },
    { code: '    if a[j] > a[j+1]', stepTypes: ['compare'] },
    { code: '      swap a[j] and a[j+1]', stepTypes: ['swap'] },
    { code: '  mark a[n-i-1] as sorted', stepTypes: ['mark-sorted'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'selection-sort': [
    { code: 'for i = 0 to n-2', stepTypes: [] },
    { code: '  minIdx = i', stepTypes: [] },
    { code: '  for j = i+1 to n-1', stepTypes: [] },
    { code: '    compare a[j] and a[minIdx]', stepTypes: ['compare'] },
    { code: '    if a[j] < a[minIdx]: minIdx = j', stepTypes: ['compare'] },
    { code: '  swap a[i] and a[minIdx]', stepTypes: ['swap'] },
    { code: '  mark a[i] as sorted', stepTypes: ['mark-sorted'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'insertion-sort': [
    { code: 'for i = 1 to n-1', stepTypes: [] },
    { code: '  key = a[i]', stepTypes: [] },
    { code: '  j = i - 1', stepTypes: [] },
    { code: '  while j >= 0 and a[j] > key', stepTypes: ['compare'] },
    { code: '    a[j+1] = a[j]  // shift right', stepTypes: ['swap'] },
    { code: '    j = j - 1', stepTypes: [] },
    { code: '  a[j+1] = key  // place key', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'merge-sort': [
    { code: 'mergeSort(a, lo, hi)', stepTypes: [] },
    { code: '  if lo >= hi: return', stepTypes: [] },
    { code: '  mid = (lo + hi) / 2', stepTypes: [] },
    { code: '  mergeSort(a, lo, mid)', stepTypes: [] },
    { code: '  mergeSort(a, mid+1, hi)', stepTypes: [] },
    { code: '  merge(a, lo, mid, hi)', stepTypes: [] },
    { code: '    copy to temp buffer', stepTypes: [] },
    { code: '    interleave smaller element', stepTypes: ['compare'] },
    { code: '    write back to array', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'quick-sort': [
    { code: 'quickSort(a, lo, hi)', stepTypes: [] },
    { code: '  pivot = a[hi]', stepTypes: ['pivot'] },
    { code: '  i = lo - 1', stepTypes: [] },
    { code: '  for j = lo to hi-1', stepTypes: [] },
    { code: '    compare a[j] and pivot', stepTypes: ['compare'] },
    { code: '    if a[j] <= pivot: swap a[++i] and a[j]', stepTypes: ['swap'] },
    { code: '  swap a[i+1] and a[hi]  // place pivot', stepTypes: ['swap', 'mark-sorted'] },
    { code: '  recurse on left and right partitions', stepTypes: [] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'heap-sort': [
    { code: 'buildMaxHeap(a)', stepTypes: [] },
    { code: '  heapify from last parent to root', stepTypes: ['compare', 'swap'] },
    { code: 'for i = n-1 down to 1', stepTypes: [] },
    { code: '  swap a[0] and a[i]  // extract max', stepTypes: ['swap'] },
    { code: '  mark a[i] as sorted', stepTypes: ['mark-sorted'] },
    { code: '  heapify(a, 0, i)  // restore heap', stepTypes: ['compare', 'swap'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'shell-sort': [
    { code: 'for each gap in Ciura sequence', stepTypes: [] },
    { code: '  for i = gap to n-1', stepTypes: [] },
    { code: '    temp = a[i]', stepTypes: [] },
    { code: '    while j >= gap and a[j-gap] > temp', stepTypes: ['compare'] },
    { code: '      a[j] = a[j-gap]  // shift', stepTypes: ['swap'] },
    { code: '      j -= gap', stepTypes: [] },
    { code: '    a[j] = temp', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'tim-sort': [
    { code: 'split into runs of size MIN_MERGE (32)', stepTypes: [] },
    { code: '  insertion sort each run', stepTypes: ['compare', 'swap'] },
    { code: 'for size = MIN_MERGE; size < n; size *= 2', stepTypes: [] },
    { code: '  merge adjacent runs', stepTypes: ['compare', 'overwrite'] },
    { code: '  write merged result back', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'intro-sort': [
    { code: 'depthLimit = 2 × floor(log₂ n)', stepTypes: [] },
    { code: 'introSort(arr, 0, n-1, depthLimit)', stepTypes: [] },
    { code: 'introSort(arr, lo, hi, depth):', stepTypes: [] },
    { code: '  if size ≤ 16: insertionSort(lo, hi)', stepTypes: ['compare', 'swap'] },
    { code: '  elif depth = 0: heapSort(lo, hi)', stepTypes: ['compare', 'swap'] },
    { code: '  else:', stepTypes: [] },
    { code: '    pivot = arr[hi]', stepTypes: ['pivot'] },
    { code: '    compare arr[j] and pivot', stepTypes: ['compare'] },
    { code: '    partition around pivot', stepTypes: ['swap'] },
    { code: '    recurse left and right halves', stepTypes: [] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'comb-sort': [
    { code: 'gap = n; sorted = false', stepTypes: [] },
    { code: 'while not sorted:', stepTypes: [] },
    { code: '  gap = max(1, floor(gap / 1.3))', stepTypes: [] },
    { code: '  sorted = true', stepTypes: [] },
    { code: '  for i = 0 to n-gap-1:', stepTypes: [] },
    { code: '    compare arr[i] and arr[i+gap]', stepTypes: ['compare'] },
    { code: '    if arr[i] > arr[i+gap]: swap; sorted = false', stepTypes: ['swap'] },
    { code: '  if gap > 1: sorted = false  // keep shrinking', stepTypes: [] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'counting-sort': [
    { code: 'find min and max values', stepTypes: [] },
    { code: 'count[v - min]++ for each v', stepTypes: [] },
    { code: 'prefix sum: count[i] += count[i-1]', stepTypes: [] },
    { code: 'write values back to array', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'tree-sort': [
    { code: '// Phase 1: build BST', stepTypes: [] },
    { code: 'for each element a[i]:', stepTypes: [] },
    { code: '  traverse tree: compare a[i] and node', stepTypes: ['compare'] },
    { code: '  go left if a[i] ≤ node, right otherwise', stepTypes: [] },
    { code: '  insert at null slot', stepTypes: ['pivot'] },
    { code: '// Phase 2: in-order readout', stepTypes: [] },
    { code: 'inOrder(root) → visit left, root, right', stepTypes: [] },
    { code: '  write back to array position i', stepTypes: ['overwrite'] },
    { code: '  mark position i as sorted', stepTypes: ['mark-sorted'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'radix-sort': [
    { code: 'for each digit position (LSD first)', stepTypes: [] },
    { code: '  bucket by current digit', stepTypes: [] },
    { code: '  collect from buckets in order', stepTypes: [] },
    { code: '  write pass result back', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'bucket-sort': [
    { code: 'create sqrt(n) buckets', stepTypes: [] },
    { code: 'distribute elements into buckets', stepTypes: [] },
    { code: '  bucket[floor(v / range * k)]', stepTypes: [] },
    { code: '  insertion sort each bucket', stepTypes: ['compare', 'swap'] },
    { code: '  concatenate sorted buckets', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'bogo-sort': [
    { code: 'while not sorted', stepTypes: [] },
    { code: '  check if array is sorted', stepTypes: ['compare'] },
    { code: '  if not sorted: shuffle randomly', stepTypes: ['swap'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'cocktail-shaker-sort': [
    { code: 'left = 0; right = n-1', stepTypes: [] },
    { code: 'while unsorted and left < right:', stepTypes: [] },
    { code: '  forward: for i = left to right-1', stepTypes: [] },
    { code: '    compare a[i] and a[i+1]', stepTypes: ['compare'] },
    { code: '    if a[i] > a[i+1]: swap', stepTypes: ['swap'] },
    { code: '  mark a[right] sorted; right--', stepTypes: ['mark-sorted'] },
    { code: '  backward: for i = right down to left+1', stepTypes: [] },
    { code: '    compare a[i-1] and a[i]', stepTypes: ['compare'] },
    { code: '    if a[i-1] > a[i]: swap', stepTypes: ['swap'] },
    { code: '  mark a[left] sorted; left++', stepTypes: ['mark-sorted'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'cycle-sort': [
    { code: 'for cycleStart = 0 to n-2:', stepTypes: [] },
    { code: '  item = a[cycleStart]; pos = cycleStart', stepTypes: [] },
    { code: '  for i = cycleStart+1 to n-1:', stepTypes: [] },
    { code: '    compare a[i] and item', stepTypes: ['compare'] },
    { code: '    if a[i] < item: pos++', stepTypes: [] },
    { code: '  if pos = cycleStart: continue', stepTypes: [] },
    { code: '  skip duplicates at pos', stepTypes: [] },
    { code: '  write item to a[pos]; save displaced', stepTypes: ['overwrite'] },
    { code: '  while pos ≠ cycleStart:', stepTypes: [] },
    { code: '    find new pos for displaced element', stepTypes: ['compare'] },
    { code: '    write displaced to a[pos]', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'gnome-sort': [
    { code: 'pos = 0', stepTypes: [] },
    { code: 'while pos < n', stepTypes: [] },
    { code: '  if pos == 0 or a[pos] >= a[pos-1]', stepTypes: ['compare'] },
    { code: '    pos++  // in order, step forward', stepTypes: [] },
    { code: '  else', stepTypes: [] },
    { code: '    swap a[pos] and a[pos-1]', stepTypes: ['swap'] },
    { code: '    pos--  // out of order, step back', stepTypes: [] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'stooge-sort': [
    { code: 'stoogeSort(a, lo, hi)', stepTypes: [] },
    { code: '  compare a[lo] and a[hi]', stepTypes: ['compare'] },
    { code: '  if a[lo] > a[hi]: swap a[lo] and a[hi]', stepTypes: ['swap'] },
    { code: '  if hi - lo < 2: return', stepTypes: [] },
    { code: '  t = floor((hi - lo + 1) / 3)', stepTypes: [] },
    { code: '  stoogeSort(a, lo, hi-t)   // first ⅔', stepTypes: [] },
    { code: '  stoogeSort(a, lo+t, hi)   // last ⅔', stepTypes: [] },
    { code: '  stoogeSort(a, lo, hi-t)   // first ⅔ again', stepTypes: [] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'pancake-sort': [
    { code: 'for size = n down to 2', stepTypes: [] },
    { code: '  find max in a[0..size-1]', stepTypes: ['compare'] },
    { code: '  flip(a, 0, maxIdx)  // bring max to top', stepTypes: ['swap'] },
    { code: '  flip(a, 0, size-1)  // place max at end', stepTypes: ['swap'] },
    { code: '  mark a[size-1] as sorted', stepTypes: ['mark-sorted'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'sleep-sort': [
    { code: 'for each element v', stepTypes: [] },
    { code: '  dispatch thread: sleep(v ms)', stepTypes: ['pivot'] },
    { code: 'each thread, on waking:', stepTypes: [] },
    { code: '  write v to next output slot', stepTypes: ['overwrite'] },
    { code: '  mark slot as arrived', stepTypes: ['mark-sorted'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'stalin-sort': [
    { code: 'max = a[0]; mark a[0] as sorted', stepTypes: ['mark-sorted'] },
    { code: 'for i = 1 to n-1', stepTypes: [] },
    { code: '  compare a[i] and max', stepTypes: ['compare'] },
    { code: '  if a[i] >= max', stepTypes: [] },
    { code: '    max = a[i]; mark a[i] as sorted', stepTypes: ['mark-sorted'] },
    { code: '  else', stepTypes: [] },
    { code: '    purge a[i] (overwrite with 0)', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'slow-sort': [
    { code: 'slowSort(a, lo, hi)', stepTypes: [] },
    { code: '  if lo >= hi: return', stepTypes: [] },
    { code: '  mid = (lo + hi) / 2', stepTypes: [] },
    { code: '  slowSort(a, lo, mid)', stepTypes: [] },
    { code: '  slowSort(a, mid+1, hi)', stepTypes: [] },
    { code: '  compare a[mid] and a[hi]', stepTypes: ['compare'] },
    { code: '  if a[mid] > a[hi]: swap', stepTypes: ['swap'] },
    { code: '  mark a[hi] as local max', stepTypes: ['mark-sorted'] },
    { code: '  slowSort(a, lo, hi-1)', stepTypes: [] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'miracle-sort': [
    { code: 'check if array is sorted', stepTypes: ['compare'] },
    { code: 'while not sorted', stepTypes: [] },
    { code: '  do nothing; await cosmic ray', stepTypes: [] },
    { code: '  re-check array', stepTypes: ['compare'] },
    { code: '  if still not sorted: miracle!', stepTypes: [] },
    { code: '    overwrite array with sorted order', stepTypes: ['overwrite'] },
    { code: 'done', stepTypes: ['done'] },
  ],
  'quantum-bogosort': [
    { code: 'observe array (superposition check)', stepTypes: ['compare'] },
    { code: 'if this universe is not sorted', stepTypes: [] },
    { code: '  collapse to sorted state', stepTypes: ['overwrite'] },
    { code: '  all unsorted universes are destroyed', stepTypes: [] },
    { code: 'the surviving universe is sorted', stepTypes: [] },
    { code: 'done', stepTypes: ['done'] },
  ],
}
